[package]
name = "encoding"
version = "0.3.0-dev"
authors = ["Kang Seonghoon <public+rust@mearie.org>"]
exclude = ["/src/index/*", "/Makefile"]
description = "Character encoding support for Rust"
homepage = "https://github.com/lifthrasiir/rust-encoding"
documentation = "https://lifthrasiir.github.io/rust-encoding/"
repository = "https://github.com/lifthrasiir/rust-encoding"
keywords = ["encoding", "unicode", "charset"]
readme = "README.md"
license = "MIT"

[lib]
name = "encoding"

[features]
no-optimized-legacy-encoding = [
	"encoding-index-singlebyte/no-optimized-legacy-encoding",
	"encoding-index-korean/no-optimized-legacy-encoding",
	"encoding-index-japanese/no-optimized-legacy-encoding",
	"encoding-index-simpchinese/no-optimized-legacy-encoding",
	"encoding-index-tradchinese/no-optimized-legacy-encoding",
]

[dependencies.encoding-types]
version = "0.2"
path = "src/types"

# version policy for index tables:
# - major: addition or deletion of index tables
# - minor: any content changes to index tables, numbered by the date
# - patch: language changes
#
# we definitely don't want to use the old index table,
# so we should use tilde requirements here.

[dependencies.encoding-index-singlebyte]
version = "~1.20160120.0"
path = "src/index/singlebyte"

[dependencies.encoding-index-korean]
version = "~1.20141219.6"
path = "src/index/korean"

[dependencies.encoding-index-japanese]
version = "~1.20141219.6"
path = "src/index/japanese"

[dependencies.encoding-index-simpchinese]
version = "~1.20160120.0"
path = "src/index/simpchinese"

[dependencies.encoding-index-tradchinese]
version = "~1.20141219.6"
path = "src/index/tradchinese"

[dev-dependencies]
getopts = "*" # for examples
