[package]
name = "encoding"
version = "0.2.31"
authors = ["Kang Seonghoon <public+rust@mearie.org>"]

description = "Character encoding support for Rust"
homepage = "https://github.com/lifthrasiir/rust-encoding"
documentation = "https://lifthrasiir.github.io/rust-encoding/"
repository = "https://github.com/lifthrasiir/rust-encoding"
keywords = ["encoding", "unicode", "charset"]
readme = "README.md"
license = "MIT"

[lib]
name = "encoding"

# version policy for index tables:
# - major: addition or deletion of index tables
# - minor: any content changes to index tables, numbered by the date
# - patch: language changes
#
# we definitely don't want to use the old index table,
# so we should use tilde requirements here.

[dependencies.encoding-index-singlebyte]
version = "~1.20141219.5"
path = "src/index/singlebyte"

[dependencies.encoding-index-korean]
name = "encoding_index_korean"
version = "~1.20141219.5"
path = "src/index/korean"

[dependencies.encoding-index-japanese]
name = "encoding_index_korean"
version = "~1.20141219.5"
path = "src/index/japanese"

[dependencies.encoding-index-simpchinese]
name = "encoding_index_simpchinese"
version = "~1.20141219.5"
path = "src/index/simpchinese"

[dependencies.encoding-index-tradchinese]
name = "encoding_index_tradchinese"
version = "~1.20141219.5"
path = "src/index/tradchinese"

[dev-dependencies]
getopts = "*" # for examples

