[package]
name = "encoding_index_tests"
version = "0.1.5"
authors = ["Kang Seonghoon <public+rust@mearie.org>"]

description = "Helper macros used to test index tables for character encodings"
homepage = "https://github.com/lifthrasiir/rust-encoding"
readme = "../../../README.md"
license = "CC0-1.0"

[lib]
name = "encoding_index_tests"
path = "index_tests.rs"
