[package]
name = "encoding-index-singlebyte"
version = "1.20160120.0"
authors = ["Kang Seonghoon <public+rust@mearie.org>"]

description = "Index tables for various single-byte character encodings"
homepage = "https://github.com/lifthrasiir/rust-encoding"
readme = "../../../README.md"
license = "CC0-1.0"

[lib]
name = "encoding_index_singlebyte"
path = "lib.rs"

[features]
no-optimized-legacy-encoding = []

[dev-dependencies.encoding_index_tests]
version = "0.1.5"
path = "../encoding_index_tests"
